apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-ui
spec:
  replicas: 1
  template:
    metadata:
      name: allure-ui
    spec:
      containers:
        - name: allure-ui
          image: frankescobar/allure-docker-service-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5252
          envFrom:
            - configMapRef:
                name: allure-ui-env
